# Site settings
title: therudes.com Communication Service
description: ""
url: "https://therudes.com"
name: "therudes.com"
destination: /var/www/therudes.com

owner_name: "Matt Rude"
owner_url: "https://mattrude.com"
owner_pgpkey: "0xc4909ee495b0761f"

# Analytics settings
google_analytics_id: UA-11737778-1

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md

plugins:
- jekyll-responsive-image
- jekyll-minifier
#- jekyll-sitemap

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
  - width: 920
  strip: true
  save_to_source: false
  cache: true

#jekyll-minifier:
#  exclude:
#  - robots.txt
#  - sitemap.xml
