# Site settings
title: therudes.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://therudes.com"
name: "therudes.com"
baseurl: ""
destination: /var/www/therudes.com

owner_name: "Matt Rude"
owner_url: "https://mattrude.com"
owner_pgpkey: "0xc4909ee495b0761f"

# Analytics settings
google_analytics_id: UA-11737778-1

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- Gemfile
- Gemfile.lock
- README.md
- CONTRIBUTING.md
- LICENSE
- site-builder.sh

plugins:
- jekyll-sitemap
- jekyll-minifier

jekyll-press:
  exclude: "robots.txt,sitemap.xml" # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
